# Generated by Django 5.1.6 on 2025-03-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_mail_alter_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mail',
        ),
    ]
